redis-server: localhost
redis-port: 6379
redis-password: none

# If left blank, server-name will be retrieved from server properties
server-id: ""

# eg. 0.europe.pool.ntp.org"
NTP-host: ""

intervals:
  tps: 3
  players: 20
  memory: 60
  heartbeat: 5
  check-others: 0

# If checking other hosts, how old a heartbeat timestamp can be (in seconds) before raising an alarm 
heartbeat-timeout: 10
