redis-server: localhost
redis-port: 6379
redis-password: none

# If left blank, server-name will be retrieved from server properties
server-id: ""

# eg. 0.europe.pool.ntp.org"
NTP-host: ""

interval: 3
check-others: false
heartbeat-timeout: 10
